pipeline {
    agent any

    environment{
        AWS_REGION = 'us-east-2'  // Set your AWS region
        APP_NAME = 'PlatformEngineeringCourse'  // Set your Elastic Beanstalk app name
        ENV_NAME = 'flask-env'  // Set your Elastic Beanstalk environment name
        PATH = "/var/lib/jenkins/.local/bin:${env.PATH}"/var/lib/jenkins/.local/bin/eb --version
    }
    stages {
        stage(Checkout){
            steps {
                git branch: 'main', url: 'https://github.com/CarlosContreras97/Platform-Engineer.git'  
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'pip install -r requirements.txt'  // Install dependencies
                }
            }
        }
        stage('Create Deployment Package') {
            steps {
                script {
                    sh 'zip -r my-app.zip *'  // Zip the application files
                }
            }
        }
        stage('Deploy to Elastic Beanstalk') {
            steps {
                script {
                        sh '''
                            /home/ec2-user/.ebcli-virtual-env/executables/eb init -p python-3.9 $APP_NAME --region $AWS_REGION  // Initialize Elastic Beanstalk app
                            /home/ec2-user/.ebcli-virtual-env/executables/eb use $ENV_NAME  // Set the environment
                            /home/ec2-user/.ebcli-virtual-env/executables/eb deploy  // Deploy to Elastic Beanstalk                        '''
                }
                
            }
        }
    }
    post {
        always {
            cleanWs()  // Clean the workspace after the build
        }
    }
}
